version: '3.8'

services:
  korea-investment-api-python:
    #image: koreainvestmentpython:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: korea-investment-api-python
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Seoul"
    #command: python3 manage.py runserver
    volumes:
      - ./logs:/logs